name: login_test
description: A new Flutter project.
# The following line prevents the package from being accidentally published to
# pub.dev using `flutter pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number is used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
# In Windows, build-name is used as the major, minor, and patch parts
# of the product and file versions while build-number is used as the build suffix.
version: 1.0.0+1

environment:
  sdk: '>=3.1.5 <4.0.0'

# Dependencies specify other packages that your package needs in order to work.
# To automatically upgrade your package dependencies to the latest versions
# consider running `flutter pub upgrade --major-versions`. Alternatively,
# dependencies can be manually updated by changing the version numbers below to
# the latest version available on pub.dev. To see which dependencies have newer
# versions available, run `flutter pub outdated`.
dependencies:
  flutter:
    sdk: flutter
  http: ^1.1.0
  shelf: ^1.1.5
  shelf_router: ^1.0.4
  postgres: ^3.3.0
  crypto: ^3.0.1
  shared_preferences: ^2.2.2
  riverpod: ^2.4.5
  flutter_riverpod: ^2.4.5
  sqflite: ^2.3.0
  path: ^1.8.3
  google_fonts: ^6.1.0
  camera: ^0.11.0+2
  barcode_scan2: ^4.3.0
  firebase_storage: ^11.5.3
  firebase_core: ^2.24.0
  firebase_auth: ^4.15.0
  firebase_app_check: ^0.2.1+8
  firebase_messaging: ^14.7.10
  image_picker: ^1.0.4
  intl: ^0.19.0
  flutter_dotenv: ^5.1.0
  timeago: ^3.6.0
  material_design_icons_flutter: ^7.0.7296
  dropdown_search: ^5.0.6
  scrollable_positioned_list: ^0.3.8
  qr_flutter: ^4.1.0
  flutter_launcher_icons: ^0.13.1
  flutter_local_notifications: ^17.2.2
  rxdart: ^0.28.0


  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons: ^1.0.2

dev_dependencies:
  flutter_test:
    sdk: flutter

  # The "flutter_lints" package below contains a set of recommended lints to
  # encourage good coding practices. The lint set provided by the package is
  # activated in the `analysis_options.yaml` file located at the root of your
  # package. See that file for information about deactivating specific lint
  # rules and activating additional ones.
  flutter_lints: ^4.0.0

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

flutter_launcher_icons:
  android: true
  image_path: "assets/ver02/images/alpha-bookstorelogodark-ver.png"

# The following section is specific to Flutter packages.
flutter:
  assets:
    - .env
    - assets/ver02/images/auto-group-an4r.png
    - assets/ver02/images/wifi.png
    - assets/ver02/images/auto-group-nig1.png
    - assets/ver02/images/ellipse-36-bg.png
    - assets/ver02/images/notification-2.png
    - assets/ver02/images/ant-design-heart-filled.png
    - assets/ver02/images/heart-2.png
    - assets/ver02/images/akar-icons-home-aUy.png
    - assets/ver02/images/textalign-justifycenter-2.png
    - assets/ver02/images/notification-2-5vZ.png
    - assets/ver02/images/left-side-oDb.png
    - assets/ver02/images/auto-group-svah.png
    - assets/ver02/images/auto-group-di57.png
    - assets/ver02/images/group.png
    - assets/ver02/images/profile-1.png
    - assets/ver02/images/wifi-xbB.png
    - assets/ver02/images/battery-XbX.png
    - assets/ver02/images/left-side-9Xf.png
    - assets/ver02/images/alpha-bookstorelogodark-ver.png
    - assets/ver02/images/search-normal-1-3-Wws.png
    - assets/ver02/images/vector.png
    - assets/ver02/images/wifi-sLm.png
    - assets/ver02/images/sf-symbol-xmarkcirclefill-NQ9.png
    - assets/ver02/images/battery-HZb.png
    - assets/ver02/images/setting-4-2.png
    - assets/ver02/images/sf-symbol-xmarkcirclefill-uMj.png
    - assets/ver02/images/vector-doX.png
    - assets/ver02/images/setting-2-1-hhT.png
    - assets/ver02/images/wifi-TAq.png
    - assets/ver02/images/auto-group-64sm.png
    - assets/ver02/images/battery-Ge5.png
    - assets/ver02/images/battery-n6d.png
    - assets/ver02/images/battery-kJM.png
    - assets/ver02/images/left-side-28Z.png
    - assets/ver02/images/sf-symbol-xmarkcirclefill-twT.png
    - assets/ver02/images/frame-17.png
    - assets/ver02/images/left-side-YKT.png
    - assets/ver02/images/left-side-tu7.png
    - assets/ver02/images/wifi-6EV.png
    - assets/ver02/images/image-103-bg.png
    - assets/ver02/images/image-100-hKF.png
    - assets/ver02/images/bi-eye-fill-YuX.png
    - assets/ver02/images/bi-eye-fill-UbT.png
    - assets/ver02/images/alpha-bookstorelogodark-ver-P9B.png
    - assets/ver02/images/alpha-bookstorelogodark-ver-Qpy.png
    - assets/ver02/images/image-102.png
    - assets/ver02/images/image-106-sTo.png
    - assets/ver02/images/image-98-mjF.png
    - assets/ver02/images/image-103.png
    - assets/ver02/images/password-not-visible-9-64.png
    - assets/default-book.png
    - assets/page-1/images/alpha-bookstorelogodark-ver.png
    - assets/page-1/images/image-100.png
    - assets/page-1/images/image-100-f9f.png
    - assets/page-1/images/image-102.png
    - assets/page-1/images/image-100-MX3.png
    - assets/page-1/images/vector.png
    - assets/page-1/images/alpha-bookstorelogodark-ver-W9s.png
    - assets/page-1/images/auto-group-gulh.png
    - assets/page-1/images/sf-symbol-xmarkcirclefill.png
    - assets/page-1/images/auto-group-mgud.png
    - assets/page-1/images/pencil.png
    - assets/page-1/images/akar-icons-home.png
    - assets/page-1/images/image-103.png
    - assets/page-1/images/setting-4-2.png
    - assets/page-1/images/user.png
    - assets/page-1/images/auto-group-fwam.png
    - assets/page-1/images/sf-symbol-xmarkcirclefill-qPb.png
    - assets/page-1/images/unlock.png
    - assets/page-1/images/auto-group-weko.png
    - assets/page-1/images/auto-group-6ngm.png
    - assets/page-1/images/.png
    - assets/page-1/images/switch-human-interface-guidelines.png
    - assets/page-1/images/reply.png
    - assets/page-1/images/auto-group-rjzv.png
    - assets/page-1/images/image-98.png
    - assets/page-1/images/pencil-fUR.png
    - assets/page-1/images/auto-group-iwut.png
    - assets/page-1/images/alpha-bookstorelogodark-ver-uUy.png
    - assets/page-1/images/frame-17.png
    - assets/page-1/images/setting-4-2-NNZ.png
    - assets/page-1/images/homenow.png
    - assets/page-1/images/auto-group-1c2h.png
    - assets/page-1/images/bi-eye-fill.png
    - assets/page-1/images/search-normal-1-3.png
    - assets/page-1/images/user-contact.png
    - assets/page-1/images/logout.png
    - assets/page-1/images/upload.png
    - assets/page-1/images/pencil-U4D.png
    - assets/page-1/images/bi-eye-fill-2Ld.png
    - assets/page-1/images/notification.png
    - assets/page-1/images/vector-yh7.png
    - assets/page-1/images/image-103-bg.png
    - assets/page-1/images/auto-group-dr7x.png
    - assets/page-1/images/switch-human-interface-guidelines-9Vw.png
    - assets/page-1/images/sf-symbol-xmarkcirclefill-mK3.png
    - assets/page-1/images/group-1411.png
    - assets/page-1/images/double-arrow-down-circle.png
    - assets/page-1/images/auto-group-tcku.png
    - assets/page-1/images/vector-Mfs.png
    - assets/page-1/images/circle-plus.png
    - assets/page-1/images/auto-group-h6cm.png
    - assets/page-1/images/info.png
    - assets/page-1/images/trash.png
    - assets/page-1/images/textalign-justifycenter-2.png
    - assets/page-1/images/image-103-Rp9.png
    - assets/page-1/images/auto-group-e3pb.png
    - assets/page-1/images/camera.png
    - assets/page-1/images/switch-human-interface-guidelines-FYH.png
    - assets/page-1/images/ellipse-36-bg.png
    - assets/page-1/images/frame-17-ZuX.png
    - assets/page-1/images/image-98-mnV.png
    - assets/page-1/images/image-103-5a5.png
    - assets/page-1/images/ellipse-36-bg-QwX.png
    - assets/page-1/images/bi-eye-fill-BKK.png
    - assets/page-1/images/auto-group-hmkh.png
    - assets/page-1/images/search-normal-1-3-q2V.png
    - assets/page-1/images/image-106.png
  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  # assets:
  #   - images/a_dot_burr.jpeg
  #   - images/a_dot_ham.jpeg

  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages