// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCpPfE0VJulseu26bcKO5vYlgqBdc2KsxE',
    appId: '1:353876759682:web:e54eb8564709baba58909b',
    messagingSenderId: '353876759682',
    projectId: 'personal-library-403717',
    authDomain: 'personal-library-403717.firebaseapp.com',
    storageBucket: 'personal-library-403717.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBCIOVL09u-XtmK-CTkpmC84Rhe9ghnNiU',
    appId: '1:353876759682:android:68921a284c3d6f2358909b',
    messagingSenderId: '353876759682',
    projectId: 'personal-library-403717',
    storageBucket: 'personal-library-403717.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyD1x-oLpWjxSJOMmlsn7v7jhHYoCvOKI9k',
    appId: '1:353876759682:ios:c19019e7ea506bb458909b',
    messagingSenderId: '353876759682',
    projectId: 'personal-library-403717',
    storageBucket: 'personal-library-403717.appspot.com',
    iosBundleId: 'com.example.loginTest',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyD1x-oLpWjxSJOMmlsn7v7jhHYoCvOKI9k',
    appId: '1:353876759682:ios:f9ff5da5b7d8d60458909b',
    messagingSenderId: '353876759682',
    projectId: 'personal-library-403717',
    storageBucket: 'personal-library-403717.appspot.com',
    iosBundleId: 'com.example.loginTest.RunnerTests',
  );
}
